import type { Metadata } from "next";
import { Pixelify_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "mavenwifey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelifySans.className} m-0 bg-[url(../public/wallpaper.jpg)] bg-fix bg-cover backdrop-blur-md backdrop-brightness-50 pixel-art`}
      >
        <div className="max-w-sm h-dvh mx-auto flex flex-col bg-[url(../public/wallpaper.jpg)] bg-fix bg-cover pixel-art">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
