import type { Metadata } from "next";
import { Geist, Geist_Mono, Pixelify_Sans, Press_Start_2P } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Wallpaper from "../public/wallpaper.jpg"

const pressStart2P = Press_Start_2P({
  weight: '400'
})

const pixelifySans = Pixelify_Sans({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "mavenwifey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelifySans.className} antialiased m-0 bg-[url(../public/wallpaper.jpg)] bg-fix bg-cover backdrop-blur-md backdrop-brightness-50`}
      >
        <div className="max-w-sm h-screen mx-auto flex flex-col bg-[url(../public/wallpaper.jpg)] bg-fix bg-cover">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
